tools:
    external_code_coverage:
      timeout: 600
    php_code_sniffer:
        enabled: true
        config:
            standard: "psr2"
        filter:
            paths: ["Source/*"]
    php_cpd:
        enabled: true
        excluded_dirs: [".dev", "vendor", "Source/Constraint/Library"]
    php_cs_fixer:
        config:
          level: psr2
        filter:
          paths: ["Source/*"]
    php_loc:
        enabled: true
        excluded_dirs: [".dev", "vendor", "Source/Constraint/Library"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["Source/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: [".dev", "vendor", "Source/Constraint/Library"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["Source/*"]
    sensiolabs_security_checker: true
    php_sim:
        enabled: true
        min_mass: 16
    php_changetracking:
        enabled: true
        bug_patterns:
            - "\bfix(?:es|ed)?\b"
        feature_patterns:
            - "\badd(?:s|ed)?\b"
            - "\bimplement(?:s|ed)?\b"
before_commands: {  }
after_commands: {  }
artifacts: {  }
build_failure_conditions: {  }
